version: '3.7'
services:
    app:
        container_name: pokedex_frontend
        build:
            dockerfile: frontend/Dockerfile
            context: .
        # restart: always
        networks:
            - pokedex_frontend_web
        ports:
            - '3000:3000'
        volumes:
            - ./frontend/:/usr/src/web
            - ./frontend/node_modules/:/usr/src/web/node_modules
    backend:
        container_name: pokedex_backend
        build:
            dockerfile: backend/Dockerfile
            context: .
        # restart: always
        networks:
            - pokedex_frontend_web
            - pokedex_database
        ports:
            - '8001:8001'
        volumes:
            - ./backend/:/usr/src/backend
        depends_on:
            - db

networks:
    pokedex_frontend_web:
        #external: true
    pokedex_database:
        #external: true
